compile:


measure:
	sudo modprobe msr
	sudo ../../RAPL/main "${RUBY_HOME}/ruby -W0 revcomp.yarv-3.yarv 0 < ../../revcomp-input25000000.txt" Ruby reverse-complement

run:
	${RUBY_HOME}/ruby -W0 revcomp.yarv-3.yarv 0 < ../../revcomp-input25000000.txt

mem:
	/usr/bin/time -v ${RUBY_HOME}/ruby -W0 revcomp.yarv-3.yarv 0 < ../../revcomp-input25000000.txt

valgrind:
	valgrind --tool=massif --stacks=yes ${RUBY_HOME}/ruby -W0 revcomp.yarv-3.yarv 0 < ../../revcomp-input25000000.txt
